#### Step6: Finetune coordinate regressor with translated image and the matching synthetic image
# Please first generate the translated img (e.g. generate_translated.sh) and copy ('init','poses','calibration') under the same dir

python train_finetune_C.py --exp_dir 'checkpoints/urban' --path_to_real 'your absolute path to the translated real urban dataset generated by ARC' \
  --path_to_syn 'your absolute path to paired synthetic urban dataset' \
  --batch_size=16 --total_epoch_num=500 --isTrain --start_epoch=0 --isdownsample --img_normalize='urban' --data_ispaired --data_augment
